name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [1.73.0]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: rustup default ${{ matrix.rust_version }}

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: |
        sudo apt-get install libssl-dev
        cargo build --verbose --locked